In [1]:
pip install transformers

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

In [2]:
from transformers import pipeline

C:\Users\jayri\anaconda3\envs\pyvizenv\lib\site-packages\torchaudio\extension\extension.py:14: UserWarning: torchaudio C++ extension is not available.
  warnings.warn('torchaudio C++ extension is not available.')
C:\Users\jayri\anaconda3\envs\pyvizenv\lib\site-packages\torchaudio\backend\utils.py:88: UserWarning: No audio backend is available.
  warnings.warn('No audio backend is available.')


In [3]:
sentiment_analysis = pipeline('sentiment-analysis')

In [17]:
pos_text =  "I feel fine and today is a sunny day"
result = sentiment_analysis(pos_text)[0]
print("Label:", result['label'])
print("Confidence Score:", result['score'])
print()

Label: POSITIVE
Confidence Score: 0.9998576641082764



In [15]:
from transformers import AutoModelForSequenceClassification
from transformers import TFAutoModelForSequenceClassification
from transformers import AutoTokenizer
import numpy as np
from scipy.special import softmax
import csv
import urllib.request
# Preprocess text (username and link placeholders)
def preprocess(text):
    new_text = []
    for t in text.split(" "):
        t = '@user' if t.startswith('@') and len(t) > 1 else t
        t = 'http' if t.startswith('http') else t
        new_text.append(t)
    return " ".join(new_text)
# Tasks:
# emoji, emotion, hate, irony, offensive, sentiment
# stance/abortion, stance/atheism, stance/climate, stance/feminist, stance/hillary
task='sentiment'
MODEL = f"cardiffnlp/twitter-roberta-base-{task}"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
# download label mapping
labels=[]
mapping_link = f"https://raw.githubusercontent.com/cardiffnlp/tweeteval/main/datasets/{task}/mapping.txt"
with urllib.request.urlopen(mapping_link) as f:
    html = f.read().decode('utf-8').split("\n")
    csvreader = csv.reader(html, delimiter='\t')
labels = [row[1] for row in csvreader if len(row) > 1]
# PT
model = AutoModelForSequenceClassification.from_pretrained(MODEL)
model.save_pretrained(MODEL)

OSError: Can't load tokenizer for 'cardiffnlp/twitter-roberta-base-sentiment'. Make sure that:

- 'cardiffnlp/twitter-roberta-base-sentiment' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'cardiffnlp/twitter-roberta-base-sentiment' is the correct path to a directory containing relevant tokenizer files



In [14]:
MODEL

'cardiffnlp/twitter-roberta-base-sentiment'

In [6]:
text = "This is what I first saw in crypto back in 2012. A new, anti-fragile financial system that doesn't break in times of stress, where ownership of assets is clear and losses are not mutualised to tax payers. This was a big two weeks for crypto and for the future financial system."
text = preprocess(text)
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
scores = output[0][0].detach().numpy()
scores = softmax(scores)
ranking = np.argsort(scores)
ranking = ranking[::-1]
for i in range(scores.shape[0]):
    l = labels[ranking[i]]
    s = scores[ranking[i]]
    print(f"{i+1}) {l} {np.round(float(s), 4)}")

NameError: name 'tokenizer' is not defined

In [7]:
import pandas as pd
comments = pd.read_csv('bitcoin_comments.csv')
comments = pd.concat([comments,pd.DataFrame(columns=labels)])

NameError: name 'labels' is not defined

In [7]:
comments

Unnamed: 0                                            comment negative  \
0            0.0  The paper is a good read but the cryptocoinsne...      NaN   
1            1.0  Isn't this old news? Or have they released an ...      NaN   
2            2.0  Bitcoin CEO yesterday said, that he will consi...      NaN   
3            3.0  Interesting read (and I admittedly have to com...      NaN   
4            4.0  Andy Bernard would like to have a few words wi...      NaN   
5            5.0  Happy to see some brilliant minds showing we c...      NaN   
6            6.0  Ivory Tower exceptionalism does not matter. Fo...      NaN   
7            7.0  This is Aquent propaganda - taking a study, ma...      NaN   
8            8.0  "4,000 Bitcoin nodes were tested"\n\nI'm not s...      NaN   
9            9.0  They need to do a China-spefic study like this...      NaN   
10          10.0  Well no, quite the opposite. The paper does no...      NaN   
11          11.0   Does anyone have a spoon? I want to cut my veins      NaN   
12          12.0  But Gavin (anointed by Satoshi) said 20 MB is ...      NaN   
13          13.0  Cornell Study Recommends 4MB Blocksize for Bit...      NaN   
14           0.0  What is it and what does it do?     \nLink det...      NaN   
15           1.0               Where are these transactions stored?      NaN   
16           2.0  Bitcoin Core Project on Twitter: "CHECKSEQUENC...      NaN   
17           0.0  Segnet4 was just created.  It combines CSV, ve...      NaN   
18           1.0  Sipa has rebased the segwit branch to include ...      NaN   
19           2.0  It depends on which version bits wannabe altco...      NaN   
20           3.0  Currently [BIP141 says](https://github.com/bit...      NaN   
21           4.0  Segregated witness: When and how does it activ...      NaN   
22           0.0  I posted on this before.  This was for me the ...      NaN   
23           1.0  Not sure why they would recommend two wallets ...      NaN   
24           2.0  But what about the withdraws? That's the most ...      NaN   
25           3.0  Why would they only allow deposits and not wit...      NaN   
26           4.0  A 50b billion $ industry which Poker Stars own...      NaN   
27           5.0  When Bovada accepts BTC withdrawal this will b...      NaN   
28           6.0  "Bovada now accepts the world’s most popular o...      NaN   
29           7.0         Let's talk when I can withdraw bitcoin. xD      NaN   
...          ...                                                ...      ...   
4166         0.0  This topic has been submitted several times. P...      NaN   
4167         1.0  Normally I wouldn't wipe my ass with shitcoins...      NaN   
4168         2.0  Man look at that chart! If that isn't market m...      NaN   
4169         3.0  Good one.\nHopefully it will help illustrate t...      NaN   
4170         4.0  Misread for a second as bitcoin has been deept...      NaN   
4171         5.0  deTHRONEd   ha ha\n\nButt wait.  The chart... ...      NaN   
4172         6.0                         Bitcoin has been dethroned      NaN   
4173         0.0  You can't turn them on.  Disappointing!\n\n(Ye...      NaN   
4174         1.0           I hope we never have to get into X-rays!      NaN   
4175         2.0  Bitcoin Rainbow Chart announces INFRARED and U...      NaN   
4176         0.0  How long until one Bitcoin is worth more than ...      NaN   
4177         1.0  I am never in favor of brigading\n\nhttps://tw...      NaN   
4178         2.0  Just remember this guy said the price of bitco...      NaN   
4179         3.0  I love bitcoin. Gold is great too. Idk why eve...      NaN   
4180         4.0  He made you his marketing bitch.\n\nGuy doesn'...      NaN   
4181         5.0  Thank you for continuing promote Bitcoin. You ...      NaN   
4182         6.0  price per unit is a dumb measure. try market c...      NaN   
4183         7.0  The most unexpected result to me is that there...      NaN   
4184  

In [8]:
for idx,row in comments.iterrows():
    text = row['comment']
    text = preprocess(text)
    encoded_input = tokenizer(text, return_tensors='pt')
    try:
        output = model(**encoded_input)
        scores = output[0][0].detach().numpy()
        scores = softmax(scores)
        comments.loc[idx,labels] = scores
        print(scores)
    except:
        print(f"Failed on {idx}")

[0.7211788  0.23831242 0.04050879]
[0.10593541 0.8630699  0.03099472]
[0.00513296 0.7064713  0.28839582]
[0.3382918  0.5109372  0.15077102]
[0.29786465 0.67212576 0.03000956]
[0.00130922 0.01473376 0.9839572 ]
[0.5070692  0.44666487 0.04626604]
[0.64521164 0.33577913 0.01900929]
[0.69426626 0.28069988 0.02503387]
[0.01639558 0.272228   0.7113764 ]
[0.5924323  0.3781079  0.02945972]
[0.7536762  0.23880893 0.00751487]
[0.10605147 0.85939133 0.03455724]
[0.01171298 0.85293543 0.1353515 ]
[0.08742739 0.8794165  0.03315615]
[0.1701301  0.80598366 0.02388625]
[0.01056908 0.6131982  0.37623268]
[0.02913716 0.67229754 0.29856536]
[0.14533997 0.7396561  0.11500391]
[0.06807281 0.90333664 0.02859045]
[0.35928574 0.5892785  0.05143571]
[0.07913748 0.900346   0.02051647]
[0.02861697 0.22265221 0.7487309 ]
[0.79239666 0.19917555 0.0084279 ]
[0.09621208 0.57233965 0.33144835]
[0.65006214 0.33119145 0.01874625]
[0.58030933 0.36338735 0.05630335]
[0.74036396 0.2289913  0.03064463]
[0.00148835 0.073676

In [10]:
comments.to_csv(r'bitcoin_comments_with_sentiment.csv')

In [11]:
comments = pd.read_csv('mtg_comments.csv')
comments = pd.concat([comments,pd.DataFrame(columns=labels)])

C:\Users\jayri\anaconda3\envs\pyvizenv\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


In [12]:
for idx,row in comments.iterrows():
    text = row['comment']
    text = preprocess(text)
    encoded_input = tokenizer(text, return_tensors='pt')
    try:
        output = model(**encoded_input)
        scores = output[0][0].detach().numpy()
        scores = softmax(scores)
        comments.loc[idx,labels] = scores
        print(scores)
    except:
        print(f"Failed on {idx}")

[0.30447176 0.5429638  0.15256451]
[0.26000988 0.6620899  0.07790017]
[0.17082937 0.72859263 0.10057789]
[0.24260934 0.67805773 0.0793329 ]
[0.32697114 0.61662215 0.05640678]
[0.5409577  0.3951409  0.06390153]
[0.09530786 0.82189906 0.08279295]
[0.03490469 0.6827104  0.282385  ]
[0.10758618 0.87307936 0.01933436]
[0.26279098 0.71709305 0.020116  ]
[0.7914451  0.1951971  0.01335784]
[0.30505532 0.5194905  0.17545412]
[0.21965173 0.753267   0.0270813 ]
[0.12572414 0.67782825 0.19644763]
[0.6343449  0.31798646 0.04766862]
[0.5834432  0.35620722 0.06034963]
[0.4039637 0.5171064 0.0789298]
[0.87783283 0.110644   0.0115232 ]
[0.6537142  0.30403027 0.04225557]
[0.48310983 0.49792317 0.018967  ]
[0.24533392 0.7073588  0.04730725]
[0.873095   0.11210384 0.01480127]
[0.13161243 0.63560206 0.23278551]
[0.02371575 0.15670246 0.8195819 ]
[0.3296608  0.5695309  0.10080829]
[0.661516   0.3175023  0.02098168]
[0.00697544 0.16263203 0.8303925 ]
[0.08232328 0.41967943 0.49799722]
[0.9199278  0.07405487 

In [13]:
comments.to_csv(r'mtg_comments_with_sentiment.csv')

In [14]:
comments = pd.read_csv('asx_comments.csv')
comments = pd.concat([comments,pd.DataFrame(columns=labels)])

C:\Users\jayri\anaconda3\envs\pyvizenv\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


In [15]:
for idx,row in comments.iterrows():
    text = row['comment']
    text = preprocess(text)
    encoded_input = tokenizer(text, return_tensors='pt')
    try:
        output = model(**encoded_input)
        scores = output[0][0].detach().numpy()
        scores = softmax(scores)
        comments.loc[idx,labels] = scores
        print(scores)
    except:
        print(f"Failed on {idx}")

[0.4015775  0.49762872 0.10079382]
[0.70815825 0.2423465  0.04949519]
[0.6474146  0.31641185 0.03617358]
[0.31550822 0.62373275 0.06075901]
[0.1395579  0.8107697  0.04967246]
[0.00763105 0.5724579  0.4199109 ]
[0.30893067 0.5139225  0.17714675]
[0.00144074 0.0324385  0.9661207 ]
[0.03015731 0.20980819 0.76003444]
[0.0034523  0.04952742 0.9470203 ]
[0.25254396 0.4286974  0.31875876]
[0.01555394 0.24344857 0.7409975 ]
[0.08106024 0.82174647 0.0971933 ]
[0.06915103 0.5496107  0.3812382 ]
[0.06543507 0.89423144 0.04033351]
[0.6428808  0.3372443  0.01987487]
[0.02755191 0.91585785 0.05659035]
[0.09576792 0.5559362  0.3482959 ]
[0.04414188 0.92513794 0.03072026]
[0.7202388  0.26518723 0.01457388]
[0.03218278 0.89620477 0.07161243]
[0.49826288 0.4768126  0.02492455]
[0.00163248 0.00605191 0.9923154 ]
[0.09964225 0.5643358  0.33602187]
[0.03280868 0.93385    0.03334153]
[0.56951004 0.39393365 0.03655634]
[0.00392846 0.11362707 0.8824445 ]
[0.34377846 0.5975107  0.05871077]
[0.20308302 0.734883

In [16]:
comments.to_csv(r'asx_comments_with_sentiment.csv')

In [17]:
comments = pd.read_csv('property_comments.csv')
comments = pd.concat([comments,pd.DataFrame(columns=labels)])

C:\Users\jayri\anaconda3\envs\pyvizenv\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


In [18]:
for idx,row in comments.iterrows():
    text = row['comment']
    text = preprocess(text)
    encoded_input = tokenizer(text, return_tensors='pt')
    try:
        output = model(**encoded_input)
        scores = output[0][0].detach().numpy()
        scores = softmax(scores)
        comments.loc[idx,labels] = scores
        print(scores)
    except:
        print(f"Failed on {idx}")

[0.31627497 0.5425256  0.14119935]
[0.7201442  0.26005906 0.0197967 ]
[0.01907241 0.90332776 0.07759964]
[0.5230939  0.45605132 0.02085477]
[0.82961804 0.15089057 0.01949139]
[0.9740749  0.02330712 0.00261789]
[0.7499183  0.22898214 0.0210996 ]
[0.6087218  0.36531538 0.02596295]
[0.03605482 0.89512753 0.06881768]
[0.03326533 0.5661841  0.4005506 ]
[0.12826042 0.5338931  0.3378464 ]
[0.74274766 0.2269497  0.03030257]
[0.06886214 0.864962   0.06617595]
[0.13644688 0.5261772  0.3373758 ]
[0.25013146 0.51700145 0.23286717]
[0.07170599 0.8626962  0.06559785]
[0.23274836 0.6623065  0.10494515]
[0.1934309  0.78001624 0.02655279]
[0.01463755 0.15135269 0.8340098 ]
[0.25203022 0.47640535 0.2715644 ]
[0.05113025 0.9081066  0.04076314]
[0.30359355 0.6669734  0.02943306]
[0.5892508  0.38668054 0.02406872]
[0.9172653  0.07807729 0.00465744]
[0.60580885 0.36612517 0.02806601]
[0.06193962 0.549527   0.38853347]
[0.28150532 0.5076287  0.21086608]
[0.0445376  0.92684764 0.02861478]
[0.01262645 0.209825

In [19]:
comments.to_csv(r'property_comments_with_sentiment.csv')

In [20]:
comments = pd.read_csv('bonds_comments.csv')
comments = pd.concat([comments,pd.DataFrame(columns=labels)])

C:\Users\jayri\anaconda3\envs\pyvizenv\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


In [21]:
for idx,row in comments.iterrows():
    text = row['comment']
    text = preprocess(text)
    encoded_input = tokenizer(text, return_tensors='pt')
    try:
        output = model(**encoded_input)
        scores = output[0][0].detach().numpy()
        scores = softmax(scores)
        comments.loc[idx,labels] = scores
        print(scores)
    except:
        print(f"Failed on {idx}")

[0.02845577 0.8798004  0.09174389]
[0.43234056 0.513586   0.05407352]
[0.0695614  0.883541   0.04689762]
[0.29571745 0.6831022  0.02118035]
[0.4201472  0.42156106 0.15829162]
[0.82641035 0.16685459 0.006735  ]
[0.09886475 0.83802396 0.0631113 ]
[0.3424484  0.57244676 0.08510491]
[0.7034994  0.26525652 0.03124414]
[0.49797815 0.4598739  0.04214799]
[0.11777271 0.5973367  0.28489065]
[0.5895927  0.34510785 0.06529938]
[0.25739053 0.7121845  0.03042497]
[0.3811221 0.589732  0.0291459]
[0.15472089 0.82361335 0.0216658 ]
[0.53697056 0.45010397 0.01292547]
[0.02040181 0.8559501  0.12364802]
[0.4794854  0.50052214 0.01999251]
[0.59020865 0.35013968 0.05965174]
[0.03440974 0.7091306  0.25645974]
[0.46765348 0.46661526 0.06573134]
[0.13135745 0.82547057 0.04317196]
[0.36477184 0.543265   0.09196315]
[0.01710559 0.34090334 0.64199114]
[0.0271658  0.8456628  0.12717141]
[0.32826415 0.6272543  0.04448161]
[0.20458934 0.76342285 0.03198795]
[0.07369936 0.898603   0.02769752]
[0.07024974 0.90162057 

In [22]:
comments.to_csv(r'bonds_comments_with_sentiment.csv')

In [15]:
comments = pd.read_csv('asx_comments_new.csv')
comments = pd.concat([comments,pd.DataFrame(columns=labels)])

NameError: name 'labels' is not defined

In [ ]:
for idx,row in comments.iterrows():
    text = row['comment']
    text = preprocess(text)
    encoded_input = tokenizer(text, return_tensors='pt')
    try:
        output = model(**encoded_input)
        scores = output[0][0].detach().numpy()
        scores = softmax(scores)
        comments.loc[idx,labels] = scores
        print(scores)
    except:
        print(f"Failed on {idx}")

In [ ]:
comments.to_csv(r'bonds_comments_with_sentiment.csv')